import enum

class UserRole(str, enum.Enum):
    CITIZEN = "CITIZEN"
    FIELD_OFFICER = "FIELD_OFFICER"
    COMMAND_ADMIN = "COMMAND_ADMIN"

class CivicCategory(str, enum.Enum):
    POTHOLE_ROAD_DAMAGE = "POTHOLE_ROAD_DAMAGE"
    GARBAGE_OVERFLOW = "GARBAGE_OVERFLOW"
    BROKEN_STREETLIGHT = "BROKEN_STREETLIGHT"
    DRAINAGE_WATERLOGGING = "DRAINAGE_WATERLOGGING"
    OTHER = "OTHER"

class SourceType(str, enum.Enum):
    GOVERNMENT = "GOVERNMENT"
    MUNICIPAL = "MUNICIPAL"
    CITIZEN = "CITIZEN"
    FIELD_TEAM = "FIELD_TEAM"
    AI_DERIVED = "AI_DERIVED"
    SYSTEM_DERIVED = "SYSTEM_DERIVED"

class ReportSyncStatus(str, enum.Enum):
    LOCAL_ONLY = "LOCAL_ONLY"
    PENDING_SYNC = "PENDING_SYNC"
    SYNCING = "SYNCING"
    SYNCED = "SYNCED"
    SYNC_FAILED = "SYNC_FAILED"

class IncidentStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_TRIAGE = "IN_TRIAGE"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    VERIFIED_CLOSED = "VERIFIED_CLOSED"
    REJECTED = "REJECTED"

class FusionDecision(str, enum.Enum):
    MATCH_CONFIRMED = "MATCH_CONFIRMED"
    LIKELY_MATCH = "LIKELY_MATCH"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    NO_MATCH = "NO_MATCH"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"

class ClosureMatchStatus(str, enum.Enum):
    LIKELY_MATCH = "LIKELY_MATCH"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    MISMATCH_SUSPECTED = "MISMATCH_SUSPECTED"
